# Generated by Django 2.1.8 on 2020-03-04 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200304_0356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='identifier',
            field=models.CharField(blank=True, default=None, max_length=40, null=True, unique=True),
        ),
    ]
